In [9]:
# networkx 是 Python 的图论库，内部既能存邻接表也能转邻接矩阵。
import networkx as nx
import numpy as np

In [2]:
# 构造图
G = nx.Graph()
G.add_edges_from([("A", "B"), ("A", "C"), ("B", "D")])

In [3]:
# 邻接表 (dict of dict)
print(dict(G.adj))

{'A': AtlasView({'B': {}, 'C': {}}), 'B': AtlasView({'A': {}, 'D': {}}), 'C': AtlasView({'A': {}}), 'D': AtlasView({'B': {}})}


In [5]:
# 邻接矩阵 (numpy array)
A = nx.to_numpy_array(G, nodelist=["A","B","C","D"])
print(A)

[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## Adjaceny List

In [10]:
# 邻接表表示
adj_list = {
    "A": ["B", "C"],
    "B": ["A", "D"],
    "C": ["A"],
    "D": ["B"]
}

# 遍历邻居
for neighbor in adj_list["A"]:
    print("A 邻居:", neighbor)


A 邻居: B
A 邻居: C


In [7]:
from collections import defaultdict

adj_list = defaultdict(list)
edges = [("A", "B"), ("A", "C"), ("B", "D")]

# 构造无向图的邻接表
for u, v in edges:
    adj_list[u].append(v)
    adj_list[v].append(u)

print(dict(adj_list))


{'A': ['B', 'C'], 'B': ['A', 'D'], 'C': ['A'], 'D': ['B']}


## Adjacency Matrix

In [8]:
vertices = ["A", "B", "C", "D"]
n = len(vertices)

# 初始化 0 矩阵
adj_matrix = [[0] * n for _ in range(n)]

edges = [("A", "B"), ("A", "C"), ("B", "D")]

# 建立索引映射：顶点 → 行列下标
index = {v: i for i, v in enumerate(vertices)}

# 填充矩阵
for u, v in edges:
    i, j = index[u], index[v]
    adj_matrix[i][j] = 1
    adj_matrix[j][i] = 1  # 无向图对称

# 打印矩阵
for row in adj_matrix:
    print(row)


[0, 1, 1, 0]
[1, 0, 0, 1]
[1, 0, 0, 0]
[0, 1, 0, 0]
